"""Core module exports"""

from mox.infrastructure.config import settings, Settings
from .version import PACKAGE_VERSION, get_version
from .llm import (
    BaseLLM,
    OpenAILLM,
    AnthropicLLM,
    MiniMaxLLM,
    OllamaLLM,
    GeminiLLM,
    DeepSeekLLM,
    CohereLLM,
    GroqLLM,
    AzureOpenAILLM,
    LLMFactory,
    ModelProvider,
    Message,
    LLMResponse,
)
from .types import (
    AttackType,
    DefenseType,
    AttackResult,
    AttackPayload,
    AttackOutcome,
    DefenseResult,
    EvaluationReport,
)
from mox.infrastructure.auth import (
    User,
    TokenManager,
    PasswordManager,
    auth_manager,
)
from .exceptions import (
    MoxException,
    ErrorCode,
    AuthenticationError,
    AuthorizationError,
    NotFoundError,
    ValidationError,
    AttackError,
    DefenseError,
    GatewayError,
    RateLimitError,
)
from mox.infrastructure.advanced_cache import (
    CacheEntry,
    CacheStats,
    CacheBackend,
    MemoryCache,
    RedisCache,
    MultiLevelCache,
    CacheManager,
    cache_key,
    cached,
)
from .patterns import (
    RefusalPatterns,
    MaliciousPatterns,
    MaliciousPatternItem,
    HarmfulKeywords,
    HelpfulIndicators,
    SanitizeReplacements,
    PatternMatch,
)
from .evaluation import (
    EvaluationResult,
    AttackEvaluator,
    RefusalPatternEvaluator,
    KeywordOverlapEvaluator,
    CompositeEvaluator,
    SemanticSimilarityEvaluator,
    LLMBasedEvaluator,
    get_default_evaluator,
    create_evaluator,
)
from .similarity import (
    word_overlap_score,
    cosine_similarity,
    semantic_similarity,
    SimilarityCalculator,
)

__all__ = [
    "settings",
    "Settings",
    "PACKAGE_VERSION",
    "get_version",
    "BaseLLM",
    "OpenAILLM",
    "AnthropicLLM",
    "MiniMaxLLM",
    "OllamaLLM",
    "GeminiLLM",
    "DeepSeekLLM",
    "CohereLLM",
    "GroqLLM",
    "AzureOpenAILLM",
    "LLMFactory",
    "ModelProvider",
    "Message",
    "LLMResponse",
    "AttackType",
    "DefenseType",
    "AttackResult",
    "AttackPayload",
    "AttackOutcome",
    "DefenseResult",
    "EvaluationReport",
    "User",
    "TokenManager",
    "PasswordManager",
    "auth_manager",
    # Exceptions
    "MoxException",
    "ErrorCode",
    "AuthenticationError",
    "AuthorizationError",
    "NotFoundError",
    "ValidationError",
    "AttackError",
    "DefenseError",
    "GatewayError",
    "RateLimitError",
    # Cache
    "CacheEntry",
    "CacheStats",
    "CacheBackend",
    "MemoryCache",
    "RedisCache",
    "MultiLevelCache",
    "CacheManager",
    "cache_key",
    "cached",
    # Patterns
    "RefusalPatterns",
    "MaliciousPatterns",
    "MaliciousPatternItem",
    "HarmfulKeywords",
    "HelpfulIndicators",
    "SanitizeReplacements",
    "PatternMatch",
    # Evaluation
    "EvaluationResult",
    "AttackEvaluator",
    "RefusalPatternEvaluator",
    "KeywordOverlapEvaluator",
    "CompositeEvaluator",
    "SemanticSimilarityEvaluator",
    "LLMBasedEvaluator",
    "get_default_evaluator",
    "create_evaluator",
    # Similarity
    "word_overlap_score",
    "cosine_similarity",
    "semantic_similarity",
    "SimilarityCalculator",
]
