"""Core module exports"""

from .config import settings, Settings
from .version import PACKAGE_VERSION, get_version
from .deprecation import (
    DeprecationLevel,
    DeprecationInfo,
    DeprecationManager,
    DeprecationError,
    FeatureRemovedError,
    get_deprecation_manager,
    deprecated,
    deprecated_class,
    check_deprecation,
    warn_deprecation,
    get_deprecation_stats,
    get_all_deprecations,
)
from .changelog import (
    ChangeType,
    ChangeEntry,
    VersionInfo,
    ChangelogManager,
    get_changelog_manager,
    get_changelog,
    get_current_version,
    get_changes_since,
    get_deprecations_since,
    get_breaking_changes_since,
    generate_changelog_markdown,
    generate_migration_guide,
)
from .llm import (
    BaseLLM,
    OpenAILLM,
    AnthropicLLM,
    MiniMaxLLM,
    OllamaLLM,
    GeminiLLM,
    DeepSeekLLM,
    CohereLLM,
    GroqLLM,
    AzureOpenAILLM,
    LLMFactory,
    ModelProvider,
    Message,
    LLMResponse,
)
from .types import (
    AttackType,
    DefenseType,
    AttackResult,
    AttackPayload,
    AttackOutcome,
    DefenseResult,
    EvaluationReport,
)
from .auth import (
    User,
    TokenManager,
    PasswordManager,
    auth_manager,
)
from .exceptions import (
    MoxException,
    ErrorCode,
    AuthenticationError,
    AuthorizationError,
    NotFoundError,
    ValidationError,
    AttackError,
    DefenseError,
    GatewayError,
    RateLimitError,
)
from .advanced_cache import (
    CacheEntry,
    CacheStats,
    CacheBackend,
    MemoryCache,
    RedisCache,
    MultiLevelCache,
    CacheManager,
    cache_key,
    cached,
)
from .error_handling import (
    ErrorSeverity,
    ErrorCategory,
    ErrorInfo,
    MoxError as MoxErrorBase,
    AttackError as AttackErrorBase,
    EvaluationError,
    LLMError,
    TimeoutError as TimeoutErrorBase,
    ErrorHandler,
    get_error_handler,
    async_error_handler,
    sync_error_handler,
    retry_on_error,
    ErrorContext,
    handle_llm_error,
    handle_attack_error,
    handle_evaluation_error,
    create_error_response,
)

__all__ = [
    "settings",
    "Settings",
    "PACKAGE_VERSION",
    "get_version",
    # 弃用管理
    "DeprecationLevel",
    "DeprecationInfo",
    "DeprecationManager",
    "DeprecationError",
    "FeatureRemovedError",
    "get_deprecation_manager",
    "deprecated",
    "deprecated_class",
    "check_deprecation",
    "warn_deprecation",
    "get_deprecation_stats",
    "get_all_deprecations",
    # 变更日志
    "ChangeType",
    "ChangeEntry",
    "VersionInfo",
    "ChangelogManager",
    "get_changelog_manager",
    "get_changelog",
    "get_current_version",
    "get_changes_since",
    "get_deprecations_since",
    "get_breaking_changes_since",
    "generate_changelog_markdown",
    "generate_migration_guide",
    # LLM
    "BaseLLM",
    "OpenAILLM",
    "AnthropicLLM",
    "MiniMaxLLM",
    "OllamaLLM",
    "GeminiLLM",
    "DeepSeekLLM",
    "CohereLLM",
    "GroqLLM",
    "AzureOpenAILLM",
    "LLMFactory",
    "ModelProvider",
    "Message",
    "LLMResponse",
    "AttackType",
    "DefenseType",
    "AttackResult",
    "AttackPayload",
    "AttackOutcome",
    "DefenseResult",
    "EvaluationReport",
    "User",
    "TokenManager",
    "PasswordManager",
    "auth_manager",
    # Exceptions
    "MoxException",
    "ErrorCode",
    "AuthenticationError",
    "AuthorizationError",
    "NotFoundError",
    "ValidationError",
    "AttackError",
    "DefenseError",
    "GatewayError",
    "RateLimitError",
    # 缓存
    "CacheEntry",
    "CacheStats",
    "CacheBackend",
    "MemoryCache",
    "RedisCache",
    "MultiLevelCache",
    "CacheManager",
    "cache_key",
    "cached",
    # 错误处理
    "ErrorSeverity",
    "ErrorCategory",
    "ErrorInfo",
    "MoxErrorBase",
    "AttackErrorBase",
    "EvaluationError",
    "LLMError",
    "TimeoutErrorBase",
    "ErrorHandler",
    "get_error_handler",
    "async_error_handler",
    "sync_error_handler",
    "retry_on_error",
    "ErrorContext",
    "handle_llm_error",
    "handle_attack_error",
    "handle_evaluation_error",
    "create_error_response",
]
